/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizQuizIdRouteImport } from './routes/quiz.$quizId'
import { Route as QuizQuizIdIndexRouteImport } from './routes/quiz.$quizId.index'
import { Route as QuizQuizIdResultsRouteImport } from './routes/quiz.$quizId.results'
import { Route as QuizQuizIdPlayRouteImport } from './routes/quiz.$quizId.play'
import { Route as QuizQuizIdLeaderboardRouteImport } from './routes/quiz.$quizId.leaderboard'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdIndexRoute = QuizQuizIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizQuizIdRoute,
} as any)
const QuizQuizIdResultsRoute = QuizQuizIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => QuizQuizIdRoute,
} as any)
const QuizQuizIdPlayRoute = QuizQuizIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => QuizQuizIdRoute,
} as any)
const QuizQuizIdLeaderboardRoute = QuizQuizIdLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => QuizQuizIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/quiz/$quizId/leaderboard': typeof QuizQuizIdLeaderboardRoute
  '/quiz/$quizId/play': typeof QuizQuizIdPlayRoute
  '/quiz/$quizId/results': typeof QuizQuizIdResultsRoute
  '/quiz/$quizId/': typeof QuizQuizIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/quiz/$quizId/leaderboard': typeof QuizQuizIdLeaderboardRoute
  '/quiz/$quizId/play': typeof QuizQuizIdPlayRoute
  '/quiz/$quizId/results': typeof QuizQuizIdResultsRoute
  '/quiz/$quizId': typeof QuizQuizIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/quiz/$quizId/leaderboard': typeof QuizQuizIdLeaderboardRoute
  '/quiz/$quizId/play': typeof QuizQuizIdPlayRoute
  '/quiz/$quizId/results': typeof QuizQuizIdResultsRoute
  '/quiz/$quizId/': typeof QuizQuizIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/quiz/$quizId'
    | '/quiz/$quizId/leaderboard'
    | '/quiz/$quizId/play'
    | '/quiz/$quizId/results'
    | '/quiz/$quizId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/quiz/$quizId/leaderboard'
    | '/quiz/$quizId/play'
    | '/quiz/$quizId/results'
    | '/quiz/$quizId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/quiz/$quizId'
    | '/quiz/$quizId/leaderboard'
    | '/quiz/$quizId/play'
    | '/quiz/$quizId/results'
    | '/quiz/$quizId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  QuizQuizIdRoute: typeof QuizQuizIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId/': {
      id: '/quiz/$quizId/'
      path: '/'
      fullPath: '/quiz/$quizId/'
      preLoaderRoute: typeof QuizQuizIdIndexRouteImport
      parentRoute: typeof QuizQuizIdRoute
    }
    '/quiz/$quizId/results': {
      id: '/quiz/$quizId/results'
      path: '/results'
      fullPath: '/quiz/$quizId/results'
      preLoaderRoute: typeof QuizQuizIdResultsRouteImport
      parentRoute: typeof QuizQuizIdRoute
    }
    '/quiz/$quizId/play': {
      id: '/quiz/$quizId/play'
      path: '/play'
      fullPath: '/quiz/$quizId/play'
      preLoaderRoute: typeof QuizQuizIdPlayRouteImport
      parentRoute: typeof QuizQuizIdRoute
    }
    '/quiz/$quizId/leaderboard': {
      id: '/quiz/$quizId/leaderboard'
      path: '/leaderboard'
      fullPath: '/quiz/$quizId/leaderboard'
      preLoaderRoute: typeof QuizQuizIdLeaderboardRouteImport
      parentRoute: typeof QuizQuizIdRoute
    }
  }
}

interface QuizQuizIdRouteChildren {
  QuizQuizIdLeaderboardRoute: typeof QuizQuizIdLeaderboardRoute
  QuizQuizIdPlayRoute: typeof QuizQuizIdPlayRoute
  QuizQuizIdResultsRoute: typeof QuizQuizIdResultsRoute
  QuizQuizIdIndexRoute: typeof QuizQuizIdIndexRoute
}

const QuizQuizIdRouteChildren: QuizQuizIdRouteChildren = {
  QuizQuizIdLeaderboardRoute: QuizQuizIdLeaderboardRoute,
  QuizQuizIdPlayRoute: QuizQuizIdPlayRoute,
  QuizQuizIdResultsRoute: QuizQuizIdResultsRoute,
  QuizQuizIdIndexRoute: QuizQuizIdIndexRoute,
}

const QuizQuizIdRouteWithChildren = QuizQuizIdRoute._addFileChildren(
  QuizQuizIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  QuizQuizIdRoute: QuizQuizIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
